// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: binary.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{1}
}

type NewScrubReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth string `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Manu string `protobuf:"bytes,2,opt,name=manu,proto3" json:"manu,omitempty"`
	Proc string `protobuf:"bytes,3,opt,name=proc,proto3" json:"proc,omitempty"`
	Vers string `protobuf:"bytes,4,opt,name=vers,proto3" json:"vers,omitempty"`
	Dscr string `protobuf:"bytes,5,opt,name=dscr,proto3" json:"dscr,omitempty"`
	Hash string `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Host string `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Hdrs string `protobuf:"bytes,8,opt,name=hdrs,proto3" json:"hdrs,omitempty"`
	Line string `protobuf:"bytes,9,opt,name=line,proto3" json:"line,omitempty"`
	Envr string `protobuf:"bytes,10,opt,name=envr,proto3" json:"envr,omitempty"`
	Poli string `protobuf:"bytes,11,opt,name=poli,proto3" json:"poli,omitempty"`
}

func (x *NewScrubReq) Reset() {
	*x = NewScrubReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewScrubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewScrubReq) ProtoMessage() {}

func (x *NewScrubReq) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewScrubReq.ProtoReflect.Descriptor instead.
func (*NewScrubReq) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{2}
}

func (x *NewScrubReq) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *NewScrubReq) GetManu() string {
	if x != nil {
		return x.Manu
	}
	return ""
}

func (x *NewScrubReq) GetProc() string {
	if x != nil {
		return x.Proc
	}
	return ""
}

func (x *NewScrubReq) GetVers() string {
	if x != nil {
		return x.Vers
	}
	return ""
}

func (x *NewScrubReq) GetDscr() string {
	if x != nil {
		return x.Dscr
	}
	return ""
}

func (x *NewScrubReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *NewScrubReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NewScrubReq) GetHdrs() string {
	if x != nil {
		return x.Hdrs
	}
	return ""
}

func (x *NewScrubReq) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *NewScrubReq) GetEnvr() string {
	if x != nil {
		return x.Envr
	}
	return ""
}

func (x *NewScrubReq) GetPoli() string {
	if x != nil {
		return x.Poli
	}
	return ""
}

type NewScrubRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scid int64 `protobuf:"varint,1,opt,name=scid,proto3" json:"scid,omitempty"`
}

func (x *NewScrubRes) Reset() {
	*x = NewScrubRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewScrubRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewScrubRes) ProtoMessage() {}

func (x *NewScrubRes) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewScrubRes.ProtoReflect.Descriptor instead.
func (*NewScrubRes) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{3}
}

func (x *NewScrubRes) GetScid() int64 {
	if x != nil {
		return x.Scid
	}
	return 0
}

type GetDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attrs map[string]string `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetDataReq) Reset() {
	*x = GetDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataReq) ProtoMessage() {}

func (x *GetDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataReq.ProtoReflect.Descriptor instead.
func (*GetDataReq) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataReq) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type PutDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutDataReq) Reset() {
	*x = PutDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataReq) ProtoMessage() {}

func (x *PutDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataReq.ProtoReflect.Descriptor instead.
func (*PutDataReq) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{5}
}

var File_binary_proto protoreflect.FileDescriptor

var file_binary_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x73, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x05, 0x0a, 0x03, 0x52,
	0x65, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x53, 0x63, 0x72, 0x75, 0x62, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x75, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72,
	0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x72, 0x6f, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x73, 0x63, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x73, 0x63, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x64, 0x72, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x64,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e, 0x76, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x6c, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6c, 0x69, 0x22, 0x21,
	0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x53, 0x63, 0x72, 0x75, 0x62, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x63, 0x69,
	0x64, 0x22, 0x7b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12,
	0x33, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61,
	0x74, 0x74, 0x72, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0c,
	0x0a, 0x0a, 0x50, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x32, 0x9e, 0x01, 0x0a,
	0x09, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x76, 0x63, 0x12, 0x36, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x53, 0x63, 0x72, 0x75, 0x62, 0x12, 0x13, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e,
	0x4e, 0x65, 0x77, 0x53, 0x63, 0x72, 0x75, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4e, 0x65, 0x77, 0x53, 0x63, 0x72, 0x75, 0x62, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x2e,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x1a, 0x0c, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x28, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0b, 0x2e, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2d, 0x76, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binary_proto_rawDescOnce sync.Once
	file_binary_proto_rawDescData = file_binary_proto_rawDesc
)

func file_binary_proto_rawDescGZIP() []byte {
	file_binary_proto_rawDescOnce.Do(func() {
		file_binary_proto_rawDescData = protoimpl.X.CompressGZIP(file_binary_proto_rawDescData)
	})
	return file_binary_proto_rawDescData
}

var file_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_binary_proto_goTypes = []interface{}{
	(*Data)(nil),        // 0: binary.Data
	(*Res)(nil),         // 1: binary.Res
	(*NewScrubReq)(nil), // 2: binary.NewScrubReq
	(*NewScrubRes)(nil), // 3: binary.NewScrubRes
	(*GetDataReq)(nil),  // 4: binary.GetDataReq
	(*PutDataReq)(nil),  // 5: binary.PutDataReq
	nil,                 // 6: binary.Data.FieldsEntry
	nil,                 // 7: binary.GetDataReq.AttrsEntry
}
var file_binary_proto_depIdxs = []int32{
	6, // 0: binary.Data.fields:type_name -> binary.Data.FieldsEntry
	7, // 1: binary.GetDataReq.attrs:type_name -> binary.GetDataReq.AttrsEntry
	2, // 2: binary.BinarySvc.NewScrub:input_type -> binary.NewScrubReq
	4, // 3: binary.BinarySvc.GetData:input_type -> binary.GetDataReq
	0, // 4: binary.BinarySvc.PutData:input_type -> binary.Data
	3, // 5: binary.BinarySvc.NewScrub:output_type -> binary.NewScrubRes
	0, // 6: binary.BinarySvc.GetData:output_type -> binary.Data
	1, // 7: binary.BinarySvc.PutData:output_type -> binary.Res
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_binary_proto_init() }
func file_binary_proto_init() {
	if File_binary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewScrubReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewScrubRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binary_proto_goTypes,
		DependencyIndexes: file_binary_proto_depIdxs,
		MessageInfos:      file_binary_proto_msgTypes,
	}.Build()
	File_binary_proto = out.File
	file_binary_proto_rawDesc = nil
	file_binary_proto_goTypes = nil
	file_binary_proto_depIdxs = nil
}
